Allow 'notes' field to be null (yaml)/None (py)
When notes field is set to null, the following is observed:

    Traceback (most recent call last):
      File "./sync_known_issues.py", line 339, in <module>
        main()
      File "./sync_known_issues.py", line 324, in main
        if issues_equal(api_known_issue, known_issue_api_object):
      File "./sync_known_issues.py", line 215, in issues_equal
        x['notes'] = x['notes'].strip()
    AttributeError: 'NoneType' object has no attribute 'strip'

Add a test and a null check to the offending code.

Signed-off-by: Dan Rue <dan.rue@linaro.org>