kselftests: Adding known intermittent failure net altnames.sh
Kernel selftest net altnames.sh fails intermittently.

  selftests: net: altnames.sh
  Error: Unknown device type.
  Cannot find device \"dummytest\"
  Device \"shortname\" does not exist.
  Cannot find device \"dummytest\"
  Device \"someveryveryveryveryveryverylongname\" does not exist.
  Cannot find device \"dummytest\"
  TEST: altnames test            [FAIL]
  Failed to add short alternative name
  Cannot find device \"dummytest\"

ref:
https://bugs.linaro.org/show_bug.cgi?id=5773

Signed-off-by: Naresh Kamboju <naresh.kamboju@linaro.org>