Add a check to ensure each test is defined once
Failure looks like:
    Traceback (most recent call last):
      File "./sync_known_issues.py", line 396, in <module>
        main()
      File "./sync_known_issues.py", line 317, in main
        s = SquadProject(project)
      File "./sync_known_issues.py", line 223, in __init__
        self.check_for_dupe_tests()
      File "./sync_known_issues.py", line 229, in check_for_dupe_tests
        assert tn not in test_names, "Error, test name {} defined twice".format(tn)
    AssertionError: Error, test name kselftest/net_reuseport_bpf_numa defined twice

Signed-off-by: Dan Rue <dan.rue@linaro.org>